server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # nacos和sentinel放在同一个网络下，才能监控到
#        server-addr: nginx.laosonga.com
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      # 开启链路监控
      web-context-unify: false
      datasource: # 配置Sentinel的持久化
        nacos:
          nacos:
            serverAddr: localhost:8848
            groupId: DEFAULT_GROUP
            dataId: order-sentinel.json
            ruleType: flow


management:
  endpoint:
    web:
      exposure:
        include: '*'

