server:
  port: 8888
spring:
  application:
    name: nacos-consumer-open
  cloud:
    nacos:
      discovery:
        server-addr: http://101.201.154.144:8848

management:
  endpoint:
    web:
      exposure:
        include: '*'